# Generated by Django 4.1.3 on 2022-11-11 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Resumes", new_name="Resume",),
        migrations.AlterModelOptions(
            name="resume",
            options={"verbose_name": "简历", "verbose_name_plural": "简历列表"},
        ),
    ]
